models_to_test:
  - 'phi3-4k-sentiment-may-24-2024-2epoches-unsloth.Q4_K_M'
  - 'phi3-4k-sentiment-may-24-2024-2epoches-unsloth.Q5_K_M'
  - 'phi3-4k-sentiment-may-24-2024-2epoches-unsloth.Q8_0'
  - 'phi3-4k-sentiment-may-24-2024-2epoches-unsloth.F16'
  - 'phi3:3.8b-mini-instruct-4k-q4_K_M'
  - 'phi3:3.8b-mini-instruct-4k-fp16'
  - 'mistral-7b-03-sentiment-may-23-2024-2epoch-unsloth.Q4_K_M'
  - 'mistral-7b-03-sentiment-may-23-2024-2epoch-unsloth.Q5_K_M'
  - 'mistral-7b-03-sentiment-may-23-2024-2epoch-unsloth.Q8_0'
  - 'mistral-7b-03-sentiment-may-23-2024-2epoch-unsloth.F16'
  - 'llama3-8b-sentiment-may-22-2024-2epoches-unsloth.Q4_K_M'
  - 'llama3-8b-sentiment-may-22-2024-2epoches-unsloth.Q5_K_M'
  - 'llama3-8b-sentiment-may-22-2024-2epoches-unsloth.Q8_0'
  - 'llama3-8b-sentiment-may-22-2024-2epoches-unsloth.F16'
  - 'llama3:8b-instruct-sentiment_analysis-q4_K_M'
  - 'llama3:8b-instruct-sentiment_analysis-q5_K_M'
  - 'llama3:8b-instruct-sentiment_analysis-q8_0'
  - 'llama3:8b-instruct-sentiment_analysis-fp16'
  - 'llama3:8b-instruct-q4_K_M'
  - 'llama3:8b-instruct-q5_K_M'
  - 'llama3:8b-instruct-q8_0'
  - 'llama3:8b-instruct-fp16'
  - 'mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q4_K_M'
  - 'mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q5_K_M'
  - 'mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q8'
  - 'mistral-7b-sentiment-may-18-2024-1epoch-unsloth.F16'
  - 'mistral:7b-instruct-q4_K_M'
  - 'mistral:7b-instruct-q5_K_M'
  - 'mistral:7b-instruct-q8_0'
  - 'mistral:7b-instruct-fp16'
  - 'dolphin-mistral:7b-v2.8-q4_K_M'
  - 'dolphin-mistral:7b-v2.8-q5_K_M'
  - 'dolphin-mistral:7b-v2.8-q8_0'
  - 'dolphin-mistral:7b-v2.8-fp16'

comparison_pairs:
  - ['llama3_8b-instruct-fp16', 'llama3_8b-instruct-sentiment_analysis-fp16']
  - ['llama3_8b-instruct-q4_K_M', 'llama3_8b-instruct-sentiment_analysis-q4_K_M']
  - ['llama3_8b-instruct-q5_K_M', 'llama3_8b-instruct-sentiment_analysis-q5_K_M']
  - ['llama3_8b-instruct-q8_0', 'llama3_8b-instruct-sentiment_analysis-q8_0']
  - ['mistral_7b-instruct-fp16', 'llama3_8b-instruct-fp16']
  - ['mistral_7b-instruct-q4_K_M', 'llama3_8b-instruct-q4_K_M']
  - ['mistral_7b-instruct-q5_K_M', 'llama3_8b-instruct-q5_K_M']
  - ['mistral_7b-instruct-q8_0', 'llama3_8b-instruct-q8_0']
  - ['dolphin-mistral_7b-v2.8-fp16', 'mistral_7b-instruct-fp16']
  - ['dolphin-mistral_7b-v2.8-q4_K_M', 'mistral_7b-instruct-q4_K_M']
  - ['dolphin-mistral_7b-v2.8-q5_K_M', 'mistral_7b-instruct-q5_K_M']
  - ['dolphin-mistral_7b-v2.8-q8_0', 'mistral_7b-instruct-q8_0']
  - ['mistral-7b-sentiment-may-18-2024-1epoch-unsloth.F16', 'mistral_7b-instruct-fp16']
  - ['mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q4_K_M', 'mistral_7b-instruct-q4_K_M']
  - ['mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q5_K_M', 'mistral_7b-instruct-q5_K_M']
  - ['mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q8', 'mistral_7b-instruct-q8_0']
  - [
      'mistral-7b-sentiment-may-18-2024-1epoch-unsloth.F16',
      'llama3_8b-instruct-sentiment_analysis-fp16',
    ]
  - [
      'mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q4_K_M',
      'llama3_8b-instruct-sentiment_analysis-q4_K_M',
    ]
  - [
      'mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q5_K_M',
      'llama3_8b-instruct-sentiment_analysis-q5_K_M',
    ]
  - [
      'mistral-7b-sentiment-may-18-2024-1epoch-unsloth.Q8',
      'llama3_8b-instruct-sentiment_analysis-q8_0',
    ]

sentiment_save_folder: 'sentiments'

sample_size: 14
report_example_sample_size: 5
ticker_symbol: 'MSFT'
max_news_age: 1
max_news_items: 20

report_output_file: 'reports/model_metrics.xlsx'
report_output_csv_file: 'reports/model_metrics.csv'
report_output_csv_folder: 'reports'
heatmaps_folder: 'heatmaps'

default_temperature: 0.2
context_window_size: 8192
num_tokens_to_predict: 1024
